package comGUI;

import java.util.Calendar;
import core.ManipuladorExcel;

public class Interface extends javax.swing.JFrame {

    public Interface() {
        initComponents();
        txtAno.setValue(Calendar.getInstance().get(Calendar.YEAR));
        txtMes.setValue(Calendar.getInstance().get(Calendar.MONTH) + 1);
    }

    private String guard1;
    private String guard2;
    private String guard3;
    private int dia;
    private int mes;
    private int ano;
    private int nGuard;
    private int[] termos = new int[5];

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupDia = new javax.swing.ButtonGroup();
        btnGrupFolgante = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtGuarda1 = new javax.swing.JTextField();
        txtGuarda2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGuarda3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbtnDia1 = new javax.swing.JRadioButton();
        rbtnDia2 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        rbtnG1 = new javax.swing.JRadioButton();
        rbtnG2 = new javax.swing.JRadioButton();
        rbtnG3 = new javax.swing.JRadioButton();
        btnGeraPlanilha = new javax.swing.JButton();
        txtAno = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMes = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("geraPlanilha 2.11");
        setResizable(false);

        jLabel1.setText("Nome do Guarda 1:");

        txtGuarda1.setText("Sebastião");

        txtGuarda2.setText("Orlando");

        jLabel2.setText("Nome do Guarda 2:");

        txtGuarda3.setText("Manoel");

        jLabel3.setText("Nome do Guarda 3:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dia da 1ª folga do mês inicial:"));

        btnGrupDia.add(rbtnDia1);
        rbtnDia1.setSelected(true);
        rbtnDia1.setText("1");

        btnGrupDia.add(rbtnDia2);
        rbtnDia2.setText("2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(rbtnDia1)
                .addGap(18, 18, 18)
                .addComponent(rbtnDia2)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbtnDia1)
                .addComponent(rbtnDia2))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Primeiro folgante do mês?"));

        btnGrupFolgante.add(rbtnG1);
        rbtnG1.setSelected(true);
        rbtnG1.setText("Guarda 1");

        btnGrupFolgante.add(rbtnG2);
        rbtnG2.setText("Guarda 2");

        btnGrupFolgante.add(rbtnG3);
        rbtnG3.setText("Guarda 3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnG1)
                    .addComponent(rbtnG2)
                    .addComponent(rbtnG3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtnG1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnG2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnG3))
        );

        btnGeraPlanilha.setText("Gerar Planilha");
        btnGeraPlanilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeraPlanilhaActionPerformed(evt);
            }
        });

        txtAno.setModel(new javax.swing.SpinnerNumberModel(1901, 1901, 2099, 1));

        jLabel4.setText("Ano Planilha:");

        jLabel5.setText("Mês Inicial:");

        txtMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtGuarda3)
                            .addComponent(txtGuarda2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGuarda1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnGeraPlanilha, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAno, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtMes))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtGuarda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtGuarda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtGuarda3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(btnGeraPlanilha, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeraPlanilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeraPlanilhaActionPerformed
        ManipuladorExcel m1 = new ManipuladorExcel("Escala de Folga");

        guard1 = txtGuarda1.getText();
        guard2 = txtGuarda2.getText();
        guard3 = txtGuarda3.getText();

        ano = (int) txtAno.getValue();
        mes = (int) txtMes.getValue();
        dia = rbtnDia1.isSelected() ? 1 : 2;
        nGuard = rbtnG1.isSelected() ? 1 : rbtnG2.isSelected() ? 2 : 3;
        termos = new int[]{dia, mes, ano, nGuard, 5};

        m1.criarCabecalhoAno(2, 2, 3, 7, ano);

        for (int i = 0; i < 4; i++, termos[4] += 2) {
            m1.criarCabecalhoMes(termos[4], termos[4], 1, 9, termos[1]);
            m1.criarCabecalhoNomeGuardas(++termos[4], 1, 4, 7, guard1, guard2, guard3);
            termos = m1.criarBlocoFolgaMes(termos[0], termos[1], termos[2], termos[3], ++termos[4]);
        }

        for (int col : new int[]{1, 4, 7}) {
            m1.larguraColuna(col, 1900);
        }

        String path = System.getProperty("user.dir");
        path += "\\ESCALA " + txtMes.getValue() + "-" + txtAno.getValue() + ".xls";

        m1.salvar(path);
        m1.abrirArquivo(path);
    }//GEN-LAST:event_btnGeraPlanilhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeraPlanilha;
    private javax.swing.ButtonGroup btnGrupDia;
    private javax.swing.ButtonGroup btnGrupFolgante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbtnDia1;
    private javax.swing.JRadioButton rbtnDia2;
    private javax.swing.JRadioButton rbtnG1;
    private javax.swing.JRadioButton rbtnG2;
    private javax.swing.JRadioButton rbtnG3;
    private javax.swing.JSpinner txtAno;
    private javax.swing.JTextField txtGuarda1;
    private javax.swing.JTextField txtGuarda2;
    private javax.swing.JTextField txtGuarda3;
    private javax.swing.JSpinner txtMes;
    // End of variables declaration//GEN-END:variables
}
